# Configure OCCT libraries to link with
macro (target_link_occt_libraries target)
  foreach (LIB ${OpenCASCADE_LIBRARIES})
    if (WIN32)
      if (EXISTS ${OpenCASCADE_LIBRARY_DIR}/${LIB}.lib)
        set(occt_lib_dir ${OpenCASCADE_LIBRARY_DIR}/${LIB}.lib)
        # message(STATUS "Adding ${occt_lib_dir}")

        target_link_libraries(${target} debug ${occt_lib_dir})
        target_link_libraries(${target} optimized ${occt_lib_dir})
      else ()
        message(FATAL_ERROR "Library ${LIB} not found in ${OpenCASCADE_LIBRARY_DIR}")
      endif ()
    elseif (APPLE)
      if (EXISTS ${OpenCASCADE_LIBRARY_DIR}/lib${LIB}.dylib)
        set(occt_lib_dir ${OpenCASCADE_LIBRARY_DIR}/lib${LIB}.dylib)
        # message(STATUS "Adding ${occt_lib_dir}")

        target_link_libraries(${target} debug ${occt_lib_dir})
        target_link_libraries(${target} optimized ${occt_lib_dir})
      else ()
        message(FATAL_ERROR "Library lib${LIB} not found in ${OpenCASCADE_LIBRARY_DIR}")
      endif ()
    elseif (UNIX)
      if (EXISTS ${OpenCASCADE_LIBRARY_DIR}/lib${LIB}.so)
        set(occt_lib_dir ${OpenCASCADE_LIBRARY_DIR}/lib${LIB}.so)
        # message(STATUS "Adding ${occt_lib_dir}")

        target_link_libraries(${target} debug ${occt_lib_dir})
        target_link_libraries(${target} optimized ${occt_lib_dir})
      else ()
        message(FATAL_ERROR "Library lib${LIB} not found in ${OpenCASCADE_LIBRARY_DIR}")
      endif ()
    endif ()
  endforeach ()
endmacro ()

# Configure OCCT libraries to link with (vcpkg)
macro (target_link_occt_libraries_vcpkg target)
  foreach (LIB ${OpenCASCADE_LIBRARIES})
    target_link_libraries(${target} debug ${LIB})
    target_link_libraries(${target} optimized ${LIB})
  endforeach ()
endmacro ()
